/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Home;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Add_Data extends javax.swing.JFrame {

    /** Creates new form Add_Data */
    public Add_Data() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stu_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stu_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stu_AL_main = new javax.swing.JComboBox<>();
        stu_AL_first = new javax.swing.JComboBox<>();
        stu_AL_secound = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bkt1_name = new javax.swing.JComboBox<>();
        bkt2_name = new javax.swing.JComboBox<>();
        stu_OL_Mathematics = new javax.swing.JComboBox<>();
        stu_OL_Science = new javax.swing.JComboBox<>();
        stu_OL_Sinhala = new javax.swing.JComboBox<>();
        stu_OL_Religion = new javax.swing.JComboBox<>();
        stu_OL_History = new javax.swing.JComboBox<>();
        stu_OL_English = new javax.swing.JComboBox<>();
        stu_OL_BKT1 = new javax.swing.JComboBox<>();
        stu_OL_BKT2 = new javax.swing.JComboBox<>();
        stu_OL_BKT3 = new javax.swing.JComboBox<>();
        bkt3_name = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Secound Subject");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student Data Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel1.setText("Data Insert Menu");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Index Number");

        stu_ID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stu_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_IDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        stu_Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("--------O/L Subjects & Results--------");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("--------STUDENT DATA--------");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("--------A/L Subjects--------");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Main Subject");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("First Subject");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Secound Subject");

        stu_AL_main.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_main.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science For Technology (SFT)" }));
        stu_AL_main.setBorder(null);
        stu_AL_main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_AL_first.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_first.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Engineering Technology (ET)", "Bio Systems Technology (BST)" }));
        stu_AL_first.setBorder(null);
        stu_AL_first.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_AL_secound.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_secound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Information And Communication Technology (ICT)", "Agro Technology" }));
        stu_AL_secound.setBorder(null);
        stu_AL_secound.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Mathematics : ");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Science :");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Religion : ");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("History : ");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("English : ");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Sinhala : ");

        bkt1_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt1_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket I", "Tamil Language", "Geography", "Commerce", "Citizenship Education" }));
        bkt1_name.setBorder(null);
        bkt1_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bkt1_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkt1_nameActionPerformed(evt);
            }
        });

        bkt2_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt2_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket II", "Eastern music", "Western Music", "Western Music", "Art", "Dancing", "English Language & Literature", "Drama Theater", "Japanese", "Sinhala Literature" }));
        bkt2_name.setBorder(null);
        bkt2_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_Mathematics.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Mathematics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Mathematics.setBorder(null);
        stu_OL_Mathematics.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stu_OL_Mathematics.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stu_OL_MathematicsItemStateChanged(evt);
            }
        });

        stu_OL_Science.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Science.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Science.setBorder(null);
        stu_OL_Science.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_Sinhala.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Sinhala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Sinhala.setBorder(null);
        stu_OL_Sinhala.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_Religion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Religion.setBorder(null);
        stu_OL_Religion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_History.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_History.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_History.setBorder(null);
        stu_OL_History.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_English.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_English.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_English.setBorder(null);
        stu_OL_English.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_BKT1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT1.setBorder(null);
        stu_OL_BKT1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_BKT2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT2.setBorder(null);
        stu_OL_BKT2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_BKT3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT3.setBorder(null);
        stu_OL_BKT3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bkt3_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt3_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket III", "Information &  Communication Technology", "Agriculture", "Health & Physical Education", "Home science", "Media Studies", "Design Technology" }));
        bkt3_name.setBorder(null);
        bkt3_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("Connection");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stu_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(stu_ID))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(214, 214, 214))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(bkt2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkt1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkt3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stu_OL_BKT2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_BKT3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_BKT1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_English, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_History, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_Sinhala, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_Science, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_Mathematics, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stu_AL_secound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stu_AL_first, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stu_AL_main, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stu_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stu_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_AL_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(stu_AL_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_AL_secound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stu_OL_Mathematics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stu_OL_Science, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_Sinhala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_English, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_BKT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkt1_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bkt2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_BKT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stu_OL_BKT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkt3_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkt1_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkt1_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkt1_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        stu_ID.setText("");
        stu_Name.setText("");
        stu_AL_main.setSelectedIndex(0);
        stu_AL_first.setSelectedIndex(0);
        stu_AL_secound.setSelectedIndex(0);
        stu_OL_Mathematics.setSelectedIndex(0);
        stu_OL_Science.setSelectedIndex(0);
        stu_OL_Sinhala.setSelectedIndex(0);
        stu_OL_Religion.setSelectedIndex(0);
        stu_OL_History.setSelectedIndex(0);
        stu_OL_English.setSelectedIndex(0);
        bkt1_name.setSelectedIndex(0);   
        stu_OL_BKT1.setSelectedIndex(0);  
        bkt2_name.setSelectedIndex(0);
        stu_OL_BKT2.setSelectedIndex(0);
        bkt3_name.setSelectedIndex(0);        
        stu_OL_BKT3.setSelectedIndex(0);        
        stu_OL_BKT1.setSelectedIndex(0);
//        stu_AL_main.setText("helo");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        dataViewer jf1 = new dataViewer();
//        jf1.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/rcc";
        String user = "root";
        String password = "";
        
        
        String ID = stu_ID.getText();
        try {
            int num = Integer.parseInt(ID);
        } catch (Exception e) {
        }
        
        String name = stu_Name.getText();
        String m_sub = stu_AL_main.getSelectedItem().toString();
        String f_sub = stu_AL_first.getSelectedItem().toString();
        String s_sub = stu_AL_secound.getSelectedItem().toString();
        String ol_maths = stu_OL_Mathematics.getSelectedItem().toString();
        String ol_science = stu_OL_Science.getSelectedItem().toString();
        String ol_sinhala = stu_OL_Sinhala.getSelectedItem().toString();
        String ol_religion = stu_OL_Religion.getSelectedItem().toString();
        String ol_history = stu_OL_History.getSelectedItem().toString();
        String ol_english = stu_OL_English.getSelectedItem().toString();
        String part_1 = bkt1_name.getSelectedItem().toString();
        String ol_part1 = stu_OL_BKT1.getSelectedItem().toString();
        String part_2 = bkt2_name.getSelectedItem().toString();
        String ol_part2 = stu_OL_BKT2.getSelectedItem().toString();
        String part_3 = bkt3_name.getSelectedItem().toString();
        String ol_part3 = stu_OL_BKT3.getSelectedItem().toString();
        
        

        try {
            if(name == "" && ID == ""){
                JOptionPane.showMessageDialog(null,"Check Name And ID");
            }
            else{
                String query = "INSERT INTO stu_data VALUES ("+ ID +",'"+ name +"', '"+ m_sub +"', '"+ f_sub +"', '"+ s_sub +"', '"+ ol_maths +"', '"+ ol_science +"', '"+ ol_sinhala +"', '"+ ol_religion +"', '"+ ol_english +"', '"+ part_1 +"', '"+ ol_part1 +"', '"+ part_2 +"', '"+ ol_part2 +"', '"+ part_3 +"', '"+ ol_part3 +"', '"+ ol_history +"')"; //ol_history
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(url, user, password);
                Statement statement = connection.createStatement();
                        
                statement.executeUpdate(query);
                stu_ID.setText("");
                stu_Name.setText("");
                stu_AL_main.setSelectedIndex(0);
                stu_AL_first.setSelectedIndex(0);
                stu_AL_secound.setSelectedIndex(0);
                stu_OL_Mathematics.setSelectedIndex(0);
                stu_OL_Science.setSelectedIndex(0);
                stu_OL_Sinhala.setSelectedIndex(0);
                stu_OL_Religion.setSelectedIndex(0);
                stu_OL_History.setSelectedIndex(0);
                stu_OL_English.setSelectedIndex(0);
                bkt1_name.setSelectedIndex(0);   
                stu_OL_BKT1.setSelectedIndex(0);  
                bkt2_name.setSelectedIndex(0);
                stu_OL_BKT2.setSelectedIndex(0);
                bkt3_name.setSelectedIndex(0);        
                stu_OL_BKT3.setSelectedIndex(0);        
                stu_OL_BKT1.setSelectedIndex(0);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR : " + e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stu_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_IDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        JOptionPane.showMessageDialog(null,"hi");
        String url = "jdbc:mysql://localhost:3306/rcc";
        String user = "root";
        String password = "";
        String query = "SELECT * FROM test";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, user, password);
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(query);
            
            String f_name;
            String l_name;
            String age;
            String line;
            while(result.next()){
                f_name = result.getString(2);
                l_name = result.getString(3);
                age = result.getString(4);
                line = f_name + " " + l_name + " 's age is " + age;
                JOptionPane.showMessageDialog(null, line);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR : " + e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void stu_OL_MathematicsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stu_OL_MathematicsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_OL_MathematicsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bkt1_name;
    private javax.swing.JComboBox<String> bkt2_name;
    private javax.swing.JComboBox<String> bkt3_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> stu_AL_first;
    private javax.swing.JComboBox<String> stu_AL_main;
    private javax.swing.JComboBox<String> stu_AL_secound;
    private javax.swing.JTextField stu_ID;
    private javax.swing.JTextField stu_Name;
    private javax.swing.JComboBox<String> stu_OL_BKT1;
    private javax.swing.JComboBox<String> stu_OL_BKT2;
    private javax.swing.JComboBox<String> stu_OL_BKT3;
    private javax.swing.JComboBox<String> stu_OL_English;
    private javax.swing.JComboBox<String> stu_OL_History;
    private javax.swing.JComboBox<String> stu_OL_Mathematics;
    private javax.swing.JComboBox<String> stu_OL_Religion;
    private javax.swing.JComboBox<String> stu_OL_Science;
    private javax.swing.JComboBox<String> stu_OL_Sinhala;
    // End of variables declaration//GEN-END:variables

}
